apiVersion: v1
kind: Namespace
metadata:
  labels:
    k8s-app: swiftkube
    pod-security.kubernetes.io/enforce: privileged
  name: swiftkube

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: swiftkube-cluster-role
  namespace: swiftkube 
rules:
- apiGroups: ["", "apps", "swiftkube.io"]
  resources: ["pods", "deployments", "swiftdeployments", "services"]
  verbs: ["get", "list", "watch", "update", "create", "delete"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: swiftkube-cluster-role-binding
subjects:
- kind: ServiceAccount
  name: swiftkube-service-account
  namespace: swiftkube 
roleRef:
  kind: ClusterRole
  name: swiftkube-cluster-role
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: swiftkube-service-account 
  namespace: swiftkube
