apiVersion: v1
kind: Namespace
metadata:
  labels:
    k8s-app: swiftkube
    pod-security.kubernetes.io/enforce: privileged
  name: swiftkube

---

apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: swift-monitor
  namespace: swiftkube
spec:
  selector:
    matchLabels:
      name: swift-monitor
  template:
    metadata:
      labels:
        name: swift-monitor
    spec:
      serviceAccountName: swiftkube-service-account
      containers:
        - name: swift-monitor 
          image: registry:5000/swiftkube/swift-monitor:dev 
          securityContext:
            privileged: true
          ports:
            - containerPort: 10000
              hostPort: 10000
              name: http
              protocol: TCP 
          volumeMounts:
            - name: cgroup
              mountPath: /sys/fs/cgroup
            - name: swapin 
              mountPath: /dev 
          imagePullPolicy: Always 
          command:
            - /usr/local/bin/swift-monitor
          env:
            - name: MY_NODE_NAME 
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
      volumes:
        - 
          name: cgroup
          hostPath:
            path: /sys/fs/cgroup
            type: Directory 
        -
          name: swapin 
          hostPath:
            path: /dev 
            type: Directory 