apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: swiftdeployments.swiftkube.io
spec:
  group: swiftkube.io
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        # schema used for validation
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                serviceName:
                  type: string 
                replicas:
                  type: integer
                runningReplicas:
                  type: integer 
                deploymentTemplate:
                  x-kubernetes-preserve-unknown-fields: true
                  type: object 
                serviceTemplate:
                  x-kubernetes-preserve-unknown-fields: true
                  type: object 
            status:
              type: object
              properties:
                runningReplicas:
                  type: integer
                availableReplicas:
                  type: integer 
  names:
    kind: SwiftDeployment
    plural: swiftdeployments
  scope: Namespaced
